[package]
name = "rust"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "rust"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
aubio = { version = "0.2.1", features = ["bindgen"] }
creak = "0.3.0"
hound = "3.5.0"
rustler = "0.28.0"
rustfft = "6.1.0"
