name: ci
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Build production image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: dexterslab/audiuslive:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
