name: deployment
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            echo "Pulling code..."
            cd ~/audius.live
            git submodule update --remote
            git reset --hard
            git pull --recurse-submodules origin main
            echo "Updating mix deps..."
            /usr/bin/mix deps.get --only prod
            echo "Compiling..."
            MIX_ENV=prod /usr/bin/mix compile
            echo "Setting up assets..."
            npm install --prefix assets
            MIX_ENV=prod /usr/bin/mix assets.deploy
            MIX_ENV=prod /usr/bin/mix phx.digest
            echo "Releasing..."
            source .env && MIX_ENV=prod /usr/bin/mix release --overwrite
            MIX_ENV=prod /usr/bin/mix ecto.migrate
            echo "Restarting server..."
            source .env && _build/prod/rel/audius_live/bin/audius_live restart
            source .env && _build/prod/rel/audius_live/bin/audius_live daemon
            echo "All done."
