name: deployment
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: audius.live
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            echo "Pulling code..."
            cd ~/audius.live
            git submodule update --remote
            git pull --recurse-submodules origin main
            echo "Updating mix deps..."
            mix deps.get --only prod
            echo "Compiling..."
            MIX_ENV=prod mix compile
            echo "Setting up assets..."
            npm install --prefix assets
            MIX_ENV=prod mix assets.deploy
            MIX_ENV=prod mix phx.digest
            echo "Releasing..."
            source .env && MIX_ENV=prod mix release --overwrite
            MIX_ENV=prod mix ecto.migrate
            echo "Stopping server..."
            _build/prod/rel/audius.live/bin/audius.live stop
            sleep 5
            echo "Starting server..."
            source .env && _build/prod/rel/audius.live/bin/audius.live daemon
            echo "All done."
